 - name: "update apt packages"
   become: true
   become_method: sudo
   apt:
     update_cache: yes

 - name: "remove dependancy that no longer required"
   become: true
   apt:
     autoremove: yes
   
