- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install NodeJS"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "install NPM"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "creates directory"
  file:
    path: ~/web
    state: directory 

- name: "install index page"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: "install apache"
  become: true
  shell: pm2 start ~/web/index.js -f
